# 
# makefile for lab1
# Marco Salazar
# February 07, 2020
#
# This makefile compiles the code necessary to run ./lab3. if there are any changes made to any of the files, it will recompile.
#

all:	lab3
	gcc -o lab3 symtable.c
